[project]
name = "autodrive-coopertitive-marl"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "mlagents==0.26.0",
    "numpy==1.23.5",
    "protobuf==3.20.3",
    "six>=1.17.0",
]
